name: Build Library using Swift Package Manager

on:
  push:
    branches:
      - '**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Install Swift
        run: |
          sudo apt-get update
          sudo apt install -y curl
          curl -s https://archive.swiftlang.xyz/install.sh | sudo bash
          sudo apt install -y swiftlang
          swift --version

      - name: Build with Swift Package Manager
        run: swift build
