name: Build Library

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Install Swift
        uses: fwal/setup-swift@v1
        with:
          swift-version: '5.9.2'

      - name: Build with Swift Package Manager
        run: swift build
